# Generated by Django 3.2 on 2023-04-07 17:25

from django.db import migrations, models
import titles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20230406_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[titles.validators.my_year_validator], verbose_name='Год'),
        ),
    ]
